version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: task-backend-container
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend